services:
  todo_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${TODO_PORT}:${TODO_PORT}"
    environment:
      - TODO_PORT=${TODO_PORT}
      - TODO_PASSWORD=${TODO_PASSWORD}
    volumes:
      - ./scheduler.db:/app/scheduler.db